In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/diabetes.csv')

y = df['Outcome']
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [3]:
X = df.drop(['Outcome'], axis=1)
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

# 4️⃣ 데이터 스케일링
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
# 5️⃣ 모델 생성
clf_rt = RandomForestClassifier(n_estimators=100, random_state=0)
# 6️⃣ 모델 학습
clf_rt.fit(X_train, y_train)
# 7️⃣ 예측
pred_rt = clf_rt.predict(X_test)
# 8️⃣ 결과 출력
print("\n--- [Diabetes] Random Forest Classifier ---")
print("Accuracy:", accuracy_score(y_test, pred_rt))
print("Confusion Matrix:\n", confusion_matrix(y_test, pred_rt))

--- [Diabetes] Random Forest Classifier ---
Accuracy: 0.7760416666666666
Confusion Matrix:
 [[116  14]
 [ 29  33]]